version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: omnidevice
      POSTGRES_PASSWORD: development
      POSTGRES_DB: omnidevice
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    environment:
      DATABASE_URL: postgresql://omnidevice:development@postgres:5432/omnidevice
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
